### ISSUE TITLE
CefSharp.Core.Runtime.DLL I can't use the program

### ISSUE THREAD

**Issue by Nexosebas** [ic3w0lf22/Roblox-Account-Manager#15]
After formatting my PC 4 times and trying everything I still don't know how to fix this error.
At first I thought it was because of the antivirus but no.
At 4 Formatting my PC before installing the Roblox ACC Manager, I completely disabled the Antivirus but even after turning off the PC and turning it on again, the Error came out. I attach a video of how it looks.

https://user-images.githubusercontent.com/86798280/124223050-969b3300-dac8-11eb-9c2b-6c4ad30d1f3c.mp4

Sorry for the Music.
PD: And it does not work to remove the folder from quarantine and put the accounts back,  the error continues to appear

**Comment by ic3w0lf22** [comment]
Try downloading and installing this
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Nexosebas** [comment]
> Try downloading and installing this
> https://www.microsoft.com/en-us/download/details.aspx?id=48145

See

https://user-images.githubusercontent.com/86798280/124223590-9d767580-dac9-11eb-8e39-2212de585433.mp4

**Comment by ic3w0lf22** [comment]
You need to restart your pc after installing that

**Comment by Nexosebas** [comment]
> You need to restart your pc after installing that

I send u DMs can u speak with me? 𝐍𝐞𝐱𝐨!#3101

**Comment by ic3w0lf22** [comment]
Issue has been fixed in release 1.9

**Comment by Wingysam** [comment]
@ic3w0lf22 I'm still getting this issue even after installing .NET framework and vc redist on a libvirt QEMU Windows 10 KVM. Any idea what could be causing this? Thanks!
